--- #YAML:1.0
name:                Storable-CouchDB
version:             0.02
abstract:            Persistence for Perl data structures in CouchDB
license:             ~
author:              
    - Michael R. Davis (mdavis@stopllc.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CouchDB::Client:               0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
